
// This file has been generated by the GUI designer. Do not modify.
namespace Menu
{
	public partial class PhoneWindow
	{
		private global::Gtk.Table mainTable;
		
		private global::Gtk.Table subTable;
		
		private global::Gtk.Button buttonCall;
		
		private global::Gtk.Table buttonsTable;
		
		private global::Gtk.Button button;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Button button2;
		
		private global::Gtk.Button button3;
		
		private global::Gtk.Button button4;
		
		private global::Gtk.Button button5;
		
		private global::Gtk.Button button6;
		
		private global::Gtk.Button button7;
		
		private global::Gtk.Button button8;
		
		private global::Gtk.Button button9;
		
		private global::Gtk.Button buttonCrvenaZvezda;
		
		private global::Gtk.Button buttonScala;
		
		private global::Gtk.Table topTable;
		
		private global::Gtk.Button exitPhoneButton;
		
		private global::Gtk.Entry phoneNo;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Menu.PhoneWindow
			this.Name = "Menu.PhoneWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("PhoneWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.AllowShrink = true;
			// Container child Menu.PhoneWindow.Gtk.Container+ContainerChild
			this.mainTable = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.mainTable.Name = "mainTable";
			this.mainTable.RowSpacing = ((uint)(6));
			this.mainTable.ColumnSpacing = ((uint)(6));
			// Container child mainTable.Gtk.Table+TableChild
			this.subTable = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.subTable.Name = "subTable";
			this.subTable.RowSpacing = ((uint)(6));
			this.subTable.ColumnSpacing = ((uint)(6));
			// Container child subTable.Gtk.Table+TableChild
			this.buttonCall = new global::Gtk.Button ();
			this.buttonCall.CanFocus = true;
			this.buttonCall.Name = "buttonCall";
			this.buttonCall.UseUnderline = true;
			this.buttonCall.FocusOnClick = false;
			this.buttonCall.Relief = ((global::Gtk.ReliefStyle)(2));
			this.buttonCall.BorderWidth = ((uint)(5));
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Menu.makeACall.png");
			this.buttonCall.Image = w1;
			this.subTable.Add (this.buttonCall);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.subTable [this.buttonCall]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(7));
			w2.YOptions = ((global::Gtk.AttachOptions)(6));
			// Container child subTable.Gtk.Table+TableChild
			this.buttonsTable = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.buttonsTable.Name = "buttonsTable";
			this.buttonsTable.RowSpacing = ((uint)(6));
			this.buttonsTable.ColumnSpacing = ((uint)(6));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button = new global::Gtk.Button ();
			this.button.CanFocus = true;
			this.button.Name = "button";
			this.button.UseUnderline = true;
			this.button.FocusOnClick = false;
			this.button.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button.BorderWidth = ((uint)(10));
			this.button.Label = global::Mono.Unix.Catalog.GetString ("0");
			this.buttonsTable.Add (this.button);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.button]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.FocusOnClick = false;
			this.button1.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button1.BorderWidth = ((uint)(10));
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("1");
			this.buttonsTable.Add (this.button1);
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.FocusOnClick = false;
			this.button2.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button2.BorderWidth = ((uint)(10));
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("2");
			this.buttonsTable.Add (this.button2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.button2]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button3 = new global::Gtk.Button ();
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.FocusOnClick = false;
			this.button3.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button3.BorderWidth = ((uint)(10));
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("3");
			this.buttonsTable.Add (this.button3);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.button3]));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.FocusOnClick = false;
			this.button4.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button4.BorderWidth = ((uint)(10));
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("4");
			this.buttonsTable.Add (this.button4);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.button4]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.FocusOnClick = false;
			this.button5.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button5.BorderWidth = ((uint)(10));
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("5");
			this.buttonsTable.Add (this.button5);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.button5]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.FocusOnClick = false;
			this.button6.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button6.BorderWidth = ((uint)(10));
			this.button6.Label = global::Mono.Unix.Catalog.GetString ("6");
			this.buttonsTable.Add (this.button6);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.button6]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.FocusOnClick = false;
			this.button7.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button7.BorderWidth = ((uint)(10));
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("7");
			this.buttonsTable.Add (this.button7);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.button7]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.FocusOnClick = false;
			this.button8.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button8.BorderWidth = ((uint)(10));
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("8");
			this.buttonsTable.Add (this.button8);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.button8]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.FocusOnClick = false;
			this.button9.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button9.BorderWidth = ((uint)(10));
			this.button9.Label = global::Mono.Unix.Catalog.GetString ("9");
			this.buttonsTable.Add (this.button9);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.button9]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.buttonCrvenaZvezda = new global::Gtk.Button ();
			this.buttonCrvenaZvezda.CanFocus = true;
			this.buttonCrvenaZvezda.Name = "buttonCrvenaZvezda";
			this.buttonCrvenaZvezda.UseUnderline = true;
			this.buttonCrvenaZvezda.FocusOnClick = false;
			this.buttonCrvenaZvezda.Relief = ((global::Gtk.ReliefStyle)(2));
			this.buttonCrvenaZvezda.BorderWidth = ((uint)(10));
			this.buttonCrvenaZvezda.Label = global::Mono.Unix.Catalog.GetString ("*");
			this.buttonsTable.Add (this.buttonCrvenaZvezda);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.buttonCrvenaZvezda]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(3));
			// Container child buttonsTable.Gtk.Table+TableChild
			this.buttonScala = new global::Gtk.Button ();
			this.buttonScala.CanFocus = true;
			this.buttonScala.Name = "buttonScala";
			this.buttonScala.UseUnderline = true;
			this.buttonScala.FocusOnClick = false;
			this.buttonScala.Relief = ((global::Gtk.ReliefStyle)(2));
			this.buttonScala.BorderWidth = ((uint)(10));
			this.buttonScala.Label = global::Mono.Unix.Catalog.GetString ("#");
			this.buttonsTable.Add (this.buttonScala);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.buttonsTable [this.buttonScala]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			this.subTable.Add (this.buttonsTable);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.subTable [this.buttonsTable]));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.mainTable.Add (this.subTable);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.mainTable [this.subTable]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child mainTable.Gtk.Table+TableChild
			this.topTable = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.topTable.Name = "topTable";
			this.topTable.RowSpacing = ((uint)(6));
			this.topTable.ColumnSpacing = ((uint)(6));
			// Container child topTable.Gtk.Table+TableChild
			this.exitPhoneButton = new global::Gtk.Button ();
			this.exitPhoneButton.CanFocus = true;
			this.exitPhoneButton.Name = "exitPhoneButton";
			this.exitPhoneButton.UseUnderline = true;
			this.exitPhoneButton.FocusOnClick = false;
			this.exitPhoneButton.Relief = ((global::Gtk.ReliefStyle)(2));
			this.exitPhoneButton.BorderWidth = ((uint)(5));
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			this.exitPhoneButton.Image = w17;
			this.topTable.Add (this.exitPhoneButton);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.topTable [this.exitPhoneButton]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child topTable.Gtk.Table+TableChild
			this.phoneNo = new global::Gtk.Entry ();
			this.phoneNo.CanFocus = true;
			this.phoneNo.Name = "phoneNo";
			this.phoneNo.IsEditable = true;
			this.phoneNo.InvisibleChar = '●';
			this.topTable.Add (this.phoneNo);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.topTable [this.phoneNo]));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			this.mainTable.Add (this.topTable);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.mainTable [this.topTable]));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.mainTable);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 467;
			this.Show ();
			this.exitPhoneButton.Clicked += new global::System.EventHandler (this.OnExitPhoneButtonClicked);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton28Clicked);
		}
	}
}
